### PR TITLE
fix: Add padding and set min height - fixed #48

### LINKED ISSUE #48: Resolve top and bottom overflow with no branch plans
resolve top and bottom overflow with no branch plans:
WhatsApp Image 2024-07-08 at 21 57 35

### PR DESCRIPTION
**Pull request by darckness**

### CODE REVIEW

File: app/(home)/plans/[branch]/page.tsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ export default async function Page(props: PageProps) {
   branch.plans = await getPlans(branch);
   if (!branch.plans.length) {
     return (
-      <div className="flex flex-col items-center justify-center font-Bree text-black h-[calc(100vh-416px)] md:px-8 px-4">
+      <div className="flex flex-col items-center justify-center font-Bree text-black min-h-[calc(100vh-416px)] md:px-8 py-4 px-4">
```
Comment (davidgaspardev) [inline app/(home)/plans/[branch]/page.tsx]:
```suggestion
      <div className="flex flex-col items-center justify-center font-Bree text-black min-h-[calc(100vh-416px)] py-8 px-4">
```

**Review by davidgaspardev — CHANGES_REQUESTED** [review]

**Review by davidgaspardev — APPROVED** [review]
